// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SubastaYaDbContext))]
    partial class SubastaYaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetalleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("Domain.Entities.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("SaldoDisponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoRetenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Billeteras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SaldoDisponible = 0m,
                            SaldoRetenido = 0m,
                            SaldoTotal = 0m,
                            UsuarioId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            SaldoDisponible = 105000m,
                            SaldoRetenido = 45000m,
                            SaldoTotal = 150000m,
                            UsuarioId = 2,
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            SaldoDisponible = 200000m,
                            SaldoRetenido = 0m,
                            SaldoTotal = 200000m,
                            UsuarioId = 3,
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            SaldoDisponible = 500m,
                            SaldoRetenido = 0m,
                            SaldoTotal = 500m,
                            UsuarioId = 4,
                            Version = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlIcono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnología",
                            UrlIcono = "tech.png"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Coleccionables",
                            UrlIcono = "col.png"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Indumentaria",
                            UrlIcono = "ropa.png"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vehículos",
                            UrlIcono = "auto.png"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Puja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPuja")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubastaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("SubastaId");

                    b.ToTable("Pujas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompradorId = 2,
                            FechaPuja = new DateTime(2026, 8, 29, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Monto = 35000m,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompradorId = 2,
                            FechaPuja = new DateTime(2026, 8, 29, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            Monto = 45000m,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompradorId = 3,
                            FechaPuja = new DateTime(2026, 8, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 25000m,
                            SubastaId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Subastas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Activa estándar",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 8, 29, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2026, 8, 29, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IncrementoMinimo = 1000m,
                            PrecioBase = 30000m,
                            Titulo = "Notebook Pro",
                            UrlImagen = "img1.png",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descripcion = "Activa crítica",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 8, 29, 12, 1, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2026, 8, 29, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IncrementoMinimo = 500m,
                            PrecioBase = 10000m,
                            Titulo = "Reloj Antiguo",
                            UrlImagen = "img2.png",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 4,
                            Descripcion = "Inicia mañana",
                            Estado = "PROGRAMADA",
                            FechaFin = new DateTime(2026, 8, 31, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IncrementoMinimo = 50000m,
                            PrecioBase = 1500000m,
                            Titulo = "Auto Usado",
                            UrlImagen = "img3.png",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descripcion = "Para liquidar",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 8, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2026, 8, 26, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IncrementoMinimo = 1000m,
                            PrecioBase = 20000m,
                            Titulo = "Monitor 24",
                            UrlImagen = "img4.png",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            Descripcion = "Nadie ofertó",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 8, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2026, 8, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IncrementoMinimo = 2000m,
                            PrecioBase = 50000m,
                            Titulo = "Campera Cuero",
                            UrlImagen = "img5.png",
                            VendedorId = 1,
                            Version = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.TransaccionLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SubastaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.HasIndex("SubastaId");

                    b.ToTable("TransaccionesLedger");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BilleteraId = 2,
                            Fecha = new DateTime(2026, 8, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 150000m,
                            Tipo = "DEPOSITO"
                        },
                        new
                        {
                            Id = 2,
                            BilleteraId = 2,
                            Fecha = new DateTime(2026, 8, 29, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            Monto = 45000m,
                            SubastaId = 1,
                            Tipo = "RETENCION"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "vendedor@test.com",
                            FechaRegistro = new DateTime(2026, 8, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Vendedor",
                            PasswordHash = "hash123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "comprador1@test.com",
                            FechaRegistro = new DateTime(2026, 8, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Comprador 1",
                            PasswordHash = "hash123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "comprador2@test.com",
                            FechaRegistro = new DateTime(2026, 8, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Comprador 2",
                            PasswordHash = "hash123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sinfondos@test.com",
                            FechaRegistro = new DateTime(2026, 8, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sin Fondos",
                            PasswordHash = "hash123"
                        });
                });

            modelBuilder.Entity("Domain.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Billetera", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("Domain.Entities.Billetera", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Puja", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Comprador")
                        .WithMany()
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Domain.Entities.Subasta", b =>
                {
                    b.HasOne("Domain.Entities.Categoria", "Categoria")
                        .WithMany("Subastas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Domain.Entities.TransaccionLedger", b =>
                {
                    b.HasOne("Domain.Entities.Billetera", "Billetera")
                        .WithMany()
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaId");

                    b.Navigation("Billetera");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Subastas");
                });

            modelBuilder.Entity("Domain.Entities.Subasta", b =>
                {
                    b.Navigation("Pujas");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Billetera")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
